FROM confluentinc/cp-kafka-connect:8.0.6

RUN confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:15.1.3 \
 && confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.9.7
